Repository stride3d/stride-community-toolkit, pull requests merged in 2024-10, with the labels that each got.

#166 feat: Render Example code improvements
  examples/code-only/Example09_Renderer/MyCustomSceneRenderer.cs
  examples/code-only/Example09_Renderer/Program.cs
  examples/code-only/Example09_Renderer/SpriteBatchRendererScript.cs
  src/Stride.CommunityToolkit/Engine/GameExtensions.cs
  src/Stride.CommunityToolkit/Rendering/Compositing/EntityDebugSceneRenderer.cs
Labels: example

#170 feat: Moved all bepu libraries into their own package
  Stride.CommunityToolkit.sln
  examples/code-only/Example_Bepu_Playground/Example_Bepu_Playground.csproj
  examples/code-only/Example_Bepu_Playground/Program.cs
  src/Stride.CommunityToolkit.Bepu/Body2DComponent.cs
  src/Stride.CommunityToolkit.Bepu/Engine/BepuGameExtensions.cs
  src/Stride.CommunityToolkit.Bepu/Engine/Primitive2DCreationOptionsWithBepu.cs
  src/Stride.CommunityToolkit.Bepu/Engine/Primitive3DCreationOptionsWithBepu.cs
  src/Stride.CommunityToolkit.Bepu/Simulation2DComponent.cs
  src/Stride.CommunityToolkit.Bepu/Stride.CommunityToolkit.Bepu.csproj
  src/Stride.CommunityToolkit/Engine/GameExtensions.cs
  src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Labels: breaking-change

#171 feat: Simple screenshot extension
  src/Stride.CommunityToolkit/Engine/GameExtensions.cs
Labels: new-feature
