Repository stride3d/stride-community-toolkit, pull requests merged in 2024-02, with the labels that each got.

#102 [Docs] Update README.md
  README.md
Labels: example, refactoring

#103 feat: Release.yml title updated
  .github/release.yml
Labels: enhancement

#104 feat: GitHub Actions updated
  .github/workflows/dotnet-nuget.yml
  .github/workflows/dotnet.yml
  .github/workflows/github-pages.yml
Labels: enhancement

#105 fix: Docs improvements and link references fixes
  docs/manual/code-only/extensions.md
  docs/manual/entity-extensions/index.md
  docs/manual/game-extensions/index.md
  src/Stride.CommunityToolkit/Engine/EntityExtensions.cs
  src/Stride.CommunityToolkit/Engine/GameExtensions.cs
  src/Stride.CommunityToolkit/Extensions/TextureExtensions.cs
Labels: documentation

#109 chore: Releatese notes added
  docs/release-notes/release-1.0.0.0-preview.17.md
Labels: documentation

#110 fix: TAG_COMMIT flag added
  .github/workflows/dotnet-nuget.yml
Labels: ci-cd

#111 fix: Adding Bepu packages references
  src/Stride.BepuPhysics._2D/Stride.BepuPhysics._2D.csproj
  src/Stride.CommunityToolkit.Skyboxes/Stride.CommunityToolkit.Skyboxes.csproj
  src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Labels: ci-cd

#113 cleaned up examples
  examples/code-only/Example_CubicleCalamity/Scripts/RaycastHandler.cs
  src/Stride.CommunityToolkit/Scripts/GizmoBillboardLetterScript.cs
Labels: engineering
