Repository stride3d/stride-community-toolkit, pull requests merged in 2024-12, with the labels that each got.

#185 chore: NuGet packages bumped
  examples/code-only/Example04_MyraUI/Example04_MyraUI.csproj
  src/Stride.CommunityToolkit.Bepu/Stride.CommunityToolkit.Bepu.csproj
  src/Stride.CommunityToolkit.Examples/Stride.CommunityToolkit.Examples.csproj
  src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGui.csproj
  src/Stride.CommunityToolkit.Skyboxes/Stride.CommunityToolkit.Skyboxes.csproj
  src/Stride.CommunityToolkit.Windows/Stride.CommunityToolkit.Windows.csproj
  src/Stride.CommunityToolkit/Module.cs
  src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Labels: engineering

#186 fix: Update imgui 224
  examples/code-only/Example11_ImGui/Example11_ImGui/Properties/launchSettings.json
  src/Stride.CommunityToolkit.ImGui/ImGuiSystem.cs
  src/Stride.CommunityToolkit.ImGui/PerfMonitor.cs
  src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGui.csproj
Labels: bug-fix

#188 feat: Other examples added to the example launcher
  src/CommonSettings.props
  src/Stride.CommunityToolkit.Examples/Providers/ExampleProvider.cs
  src/Stride.CommunityToolkit.Examples/Stride.CommunityToolkit.Examples.csproj
Labels: example
