Repository stride3d/stride-community-toolkit, pull requests merged in 2024-11, with the labels that each got.

#172 refactor: Code consistency updates
  examples/code-only/Example11_ImGui/Example11_ImGui/Example11_ImGui.csproj
  examples/code-only/Example11_ImGui/Example11_ImGui/Program.cs
  src/Stride.CommunityToolkit.Bepu/Engine/BepuGameExtensions.cs
  src/Stride.CommunityToolkit.Bepu/Engine/Primitive2DCreationOptionsWithBepu.cs
  src/Stride.CommunityToolkit.Bepu/Engine/Primitive3DCreationOptionsWithBepu.cs
  src/Stride.CommunityToolkit.Bepu/Stride.CommunityToolkit.Bepu.csproj
  src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGuiDebug.csproj
  src/Stride.CommunityToolkit.Skyboxes/Stride.CommunityToolkit.Skyboxes.csproj
  src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Labels: engineering

#173 chore: Clean up of unused GitHub actions
  .github/workflows/dotnet-nuget-self-hosted.yml
  .github/workflows/dotnet-self-hosted.yml
  Stride.CommunityToolkit.sln
Labels: ci-cd

#174 feat: GitHub action updates
  .github/workflows/dotnet-nuget.yml
  .github/workflows/dotnet.yml
  Stride.CommunityToolkit.sln
  examples/code-only/Example11_ImGui/Example11_ImGui/Example11_ImGui.csproj
  examples/code-only/Example11_ImGui/Example11_ImGui/Program.cs
  src/Stride.CommunityToolkit.ImGui/BaseWindow.cs
  src/Stride.CommunityToolkit.ImGui/HierarchyView.cs
  src/Stride.CommunityToolkit.ImGui/ImGuiExtension.cs
  src/Stride.CommunityToolkit.ImGui/ImGuiSystem.cs
  src/Stride.CommunityToolkit.ImGui/Inspector.cs
  src/Stride.CommunityToolkit.ImGui/LightweightTimer.cs
  src/Stride.CommunityToolkit.ImGui/PerfMonitor.cs
  src/Stride.CommunityToolkit.ImGui/README.md
  src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGui.csproj
  src/Stride.CommunityToolkit.ImGui/XMLDocumentation.cs
Labels: ci-cd

#178 chore: NuGet packages bumped
  .gitignore
  examples/code-only/Example_Bepu_Playground/Program.cs
  src/Stride.CommunityToolkit.Bepu/Engine/Primitive2DCreationOptionsWithBepu.cs
  src/Stride.CommunityToolkit.Bepu/Engine/Primitive3DCreationOptionsWithBepu.cs
  src/Stride.CommunityToolkit.Bepu/Simulation2DComponent.cs
  src/Stride.CommunityToolkit.Bepu/Stride.CommunityToolkit.Bepu.csproj
  src/Stride.CommunityToolkit.Examples/Stride.CommunityToolkit.Examples.csproj
  src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGui.csproj
  src/Stride.CommunityToolkit.Skyboxes/Stride.CommunityToolkit.Skyboxes.csproj
  src/Stride.CommunityToolkit.Windows/Stride.CommunityToolkit.Windows.csproj
  src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Labels: engineering

#179 fix: Fixed Skybox environemnt light generation
  src/Stride.CommunityToolkit.Skyboxes/GameExtensions.cs
  src/Stride.CommunityToolkit.Skyboxes/SkyboxGenerator.cs
Labels: bug-fix
