Repository stride3d/stride-community-toolkit, pull requests merged in 2025-08, with the labels that each got.

#285 Fix: NextPoint methods in RandomExtensions only generating random points on a line
  src/Stride.CommunityToolkit/Mathematics/RandomExtensions.cs
Labels: bug-fix

#287 fix: Xml comments improvements
  src/Stride.CommunityToolkit/Engine/EntityExtensions.cs
  src/Stride.CommunityToolkit/Engine/PrimitiveCreationOptions.cs
  src/Stride.CommunityToolkit/Games/GameExtensions.cs
  src/Stride.CommunityToolkit/Mathematics/Easing.Double.cs
  src/Stride.CommunityToolkit/Mathematics/Easing.Single.cs
  src/Stride.CommunityToolkit/Mathematics/RandomExtensions.cs
  src/Stride.CommunityToolkit/Physics/FloatRGBAConverter.cs
  src/Stride.CommunityToolkit/Physics/HeightmapExtensions.cs
  src/Stride.CommunityToolkit/Physics/VertexTypePosTexNormColor.cs
  src/Stride.CommunityToolkit/Rendering/Gizmos/Letter3D.cs
  src/Stride.CommunityToolkit/Rendering/ProceduralModels/CapsuleProceduralModel.cs
  src/Stride.CommunityToolkit/Rendering/ProceduralModels/CircleProceduralModel.cs
  src/Stride.CommunityToolkit/Rendering/ProceduralModels/PolygonProceduralModel.cs
  src/Stride.CommunityToolkit/Rendering/ProceduralModels/RectangleProceduralModel.cs
  src/Stride.CommunityToolkit/Rendering/ProceduralModels/TriangleProceduralModel.cs
  src/Stride.CommunityToolkit/Rendering/ProceduralModels/TriangularPrismProceduralModel.cs
  src/Stride.CommunityToolkit/Rendering/Utilities/IndexingType.cs
  src/Stride.CommunityToolkit/Scripts/Basic2DCameraController.cs
  src/Stride.CommunityToolkit/Scripts/Basic3DCameraController.cs
  src/Stride.CommunityToolkit/Scripts/GameProfiler.cs
  src/Stride.CommunityToolkit/Scripts/GizmoBillboardLetterScript.cs
Labels: engineering

#290 refactor: Documentation updates and code refactoring
  .github/copilot-instructions.md
  docs/docfx.json
  docs/includes/libraries.md
  docs/index.md
  docs/manual/physics-extensions/index.md
  examples/code-only/Example01_Basic3DScene/Example01_Basic3DScene.csproj
  examples/code-only/Example07_CubeClicker/Example07_CubeClicker.csproj
  examples/code-only/Example07_CubeClicker/Program.cs
  examples/code-only/Example07_CubeClicker/Scripts/ClickHandlerComponent.cs
  examples/code-only/Example11_ImGui/Example11_ImGui.csproj
  examples/code-only/Example11_ImGui/Program.cs
  examples/code-only/Example17_SignalR/Example17_SignalR.csproj
  examples/code-only/Example17_SignalR_Blazor/Example17_SignalR_Blazor.csproj
  examples/code-only/Example_CubicleCalamity/CubeStacker.cs
  examples/code-only/Example_CubicleCalamity_BulletPhysics/CubeStacker.cs
  src/Stride.CommunityToolkit.Bepu/Bepu2DPhysicsOptions.cs
  src/Stride.CommunityToolkit.Bepu/Bepu3DPhysicsOptions.cs
  src/Stride.CommunityToolkit.Bepu/GameExtensions.cs
  src/Stride.CommunityToolkit.Bullet/Bullet2DPhysicsOptions.cs
  src/Stride.CommunityToolkit.Bullet/Bullet3DPhysicsOptions.cs
  src/Stride.CommunityToolkit.Bullet/GameExtensions.cs
  src/Stride.CommunityToolkit.Examples/Providers/ExampleProvider.cs
  src/Stride.CommunityToolkit.Examples/Providers/ExampleProvider2.cs
  src/Stride.CommunityToolkit/Engine/EntityExtensions.cs
  src/Stride.CommunityToolkit/Engine/Primitive2DCreationOptions.cs
  src/Stride.CommunityToolkit/Engine/Primitive2DEntityOptions.cs
  src/Stride.CommunityToolkit/Engine/Primitive3DCreationOptions.cs
  src/Stride.CommunityToolkit/Engine/Primitive3DEntityOptions.cs
  src/Stride.CommunityToolkit/Engine/PrimitiveCreationOptions.cs
  src/Stride.CommunityToolkit/Engine/PrimitiveEntityOptions.cs
  src/Stride.CommunityToolkit/Games/GameExtensions.cs
  src/Stride.CommunityToolkit/Scripts/Basic3DCameraController.cs
Labels: engineering

#295 chore: NuGet packages deployment changed to native
  .github/workflows/dotnet-nuget.yml
Labels: ci-cd
