Repository stride3d/stride-community-toolkit, pull requests merged in 2025-02, with the labels that each got.

#203 feat: New example added - Example01_Basic3DScene_MeshLine
  Stride.CommunityToolkit.sln
  examples/code-only/Example01_Basic3DScene_MeshLine/Example01_Basic3DScene_MeshLine.csproj
  examples/code-only/Example01_Basic3DScene_MeshLine/NamespaceAnchor.cs
  examples/code-only/Example01_Basic3DScene_MeshLine/Program.cs
  examples/code-only/Example14_Raycast/Program.cs
Labels: example

#204 docs: Update troubleshooting guide
  docs/manual/troubleshooting.md
  docs/run.bat
Labels: documentation

#205 fix: Fixed and enabled skybox environment map generation
  src/Stride.CommunityToolkit.Skyboxes/SkyboxGenerator.cs
Labels: bug-fix, refactoring

#207 feat: Add dependabot
  .github/dependabot.yml
  Stride.CommunityToolkit.sln
Labels: ci-cd

#228 chore: NuGet packages bumped and dependabot conf updated
  .github/dependabot.yml
  src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Labels: ci-cd
