Repository stride3d/stride-community-toolkit, pull requests merged in 2025-01, with the labels that each got.

#190 chore: Stride updates
  src/Stride.CommunityToolkit.Bepu/Stride.CommunityToolkit.Bepu.csproj
  src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGui.csproj
  src/Stride.CommunityToolkit.Skyboxes/Stride.CommunityToolkit.Skyboxes.csproj
  src/Stride.CommunityToolkit.Windows/Stride.CommunityToolkit.Windows.csproj
  src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Labels: engineering

#194 Refactoring, consistency updates, docs updates.
  .github/workflows/dotnet.yml
  docs/contributing/documentation/index.md
  docs/contributing/index.md
  docs/contributing/major-release-workflow.md
  docs/contributing/toc.yml
  docs/contributing/toolkit/index.md
  docs/contributing/toolkit/library-project.md
  docs/docfx.json
  docs/includes/libraries.md
  docs/manual/code-only/create-project.md
  docs/manual/toc.yml
  docs/release-notes/release-1.0.0.0-preview.41-48.md
  docs/release-notes/release-1.0.0.0-preview.49.md
  docs/release-notes/toc.yml
  docs/run.bat
  docs/toc.yml
  src/Stride.CommunityToolkit.DebugShapes/Stride.CommunityToolkit.DebugShapes.csproj
  src/Stride.CommunityToolkit.ImGui/Stride.CommunityToolkit.ImGui.csproj
Labels: documentation, engineering

#195 ci-cd: DebugShapes project added
  .github/workflows/dotnet-nuget.yml
  .github/workflows/dotnet.yml
  docs/contributing/toolkit/library-project.md
Labels: ci-cd

#196 ci-cd: Action name correction
  .github/workflows/dotnet-nuget.yml
Labels: ci-cd

#197 refactor!: Remove package version and .sdpkg packaging
  src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Labels: engineering

#198 fix: Include .sdpkg files in package output
  src/Stride.CommunityToolkit/Stride.CommunityToolkit.csproj
Labels: engineering
